baseURL = 'https://example.org/'
languageCode = 'zh-cn'
title = '我的极简博客'
author = '神神叨叨'
theme = 'minimal-apple'

[params]
  description = '一个极简风格、苹果官网风格的私人博客，仅供自己使用。'
  robots = 'noindex, nofollow'
  author = '神神叨叨'
  avatar = 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?auto=format&fit=crop&w=150&q=80'
  heroImage = 'https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=1200&q=80'
  defaultImage = 'https://images.unsplash.com/photo-1486312338219-ce68d2c6f44d?auto=format&fit=crop&w=600&q=80'

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    style = 'github'
    lineNos = false
    noClasses = false

[outputs]
  home = ["HTML", "RSS", "JSON"]

[related]
  includeNewer = true
  threshold = 80
  toLower = false
  [[related.indices]]
    name = "tags"
    weight = 100
  [[related.indices]]
    name = "categories"
    weight = 80
